// SUCCESS
const DARK_SUCCESS_HEX = "#00FF00";
const LIGHT_SUCCESS_HEX = "#009688";

const DARK_SUCCESS = "green-500";
const LIGHT_SUCCESS = "green-500";

// STANDARD
const DARK_STANDARD = "orange-500";
const LIGHT_STANDARD = "orange-500";

// const SEC_DARK_STANDARD = "blue-500";
// const SEC_LIGHT_STANDARD = "blue-500";

// DANGER
const DARK_DANGER_HEX = "#FF0000";
const LIGHT_DANGER_HEX = "#FF5722";

const DARK_DANGER = "red-500";
const LIGHT_DANGER = "red-500";

// SCALES
const DARK_SCALE_3 = [DARK_SUCCESS_HEX, "#FFFF00", DARK_DANGER_HEX];
const LIGHT_SCALE_3 = [LIGHT_SUCCESS_HEX, "#FF9800", "#795548"];

export {
  DARK_SUCCESS,
  LIGHT_SUCCESS,
  DARK_DANGER,
  LIGHT_DANGER,
  DARK_STANDARD,
  LIGHT_STANDARD,
  DARK_SCALE_3,
  LIGHT_SCALE_3,
};
