import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./(site)/components/theme-provider";
import { ChangeTheme } from "./(site)/components/ChangeTheme";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gestionale",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <SidebarProvider defaultOpen={false}>
            
            {children}
            <Toaster richColors position="bottom-center" duration={1500} />
            <div className="fixed bottom-4 right-4 hover:cursor-pointer">
              <ChangeTheme />
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
